spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database
    username: airtu
    password:
    h2:
      console:
        enabled: true
        path: /h2
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

